// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NursingEducationalBackend.Models;

#nullable disable

namespace NursingEducationalBackend.Migrations
{
    [DbContext(typeof(NursingDbContext))]
    [Migration("20260211225800_AddAcuteRotation")]
    partial class AddAcuteRotation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.AssessmentSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("TableRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentTypeId");

                    b.HasIndex("RecordId");

                    b.ToTable("AssessmentSubmissions");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.AssessmentType", b =>
                {
                    b.Property<int>("AssessmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssessmentTypeId");

                    b.ToTable("AssessmentTypes");

                    b.HasData(
                        new
                        {
                            AssessmentTypeId = 1,
                            Name = "ADLs",
                            RouteKey = "ADL"
                        },
                        new
                        {
                            AssessmentTypeId = 2,
                            Name = "Behaviour",
                            RouteKey = "Behaviour"
                        },
                        new
                        {
                            AssessmentTypeId = 3,
                            Name = "Cognitive",
                            RouteKey = "Cognitive"
                        },
                        new
                        {
                            AssessmentTypeId = 4,
                            Name = "Elimination",
                            RouteKey = "Elimination"
                        },
                        new
                        {
                            AssessmentTypeId = 5,
                            Name = "Mobility And Safety",
                            RouteKey = "MobilityAndSafety"
                        },
                        new
                        {
                            AssessmentTypeId = 6,
                            Name = "Nutrition",
                            RouteKey = "Nutrition"
                        },
                        new
                        {
                            AssessmentTypeId = 7,
                            Name = "Progress Note",
                            RouteKey = "ProgressNote"
                        },
                        new
                        {
                            AssessmentTypeId = 8,
                            Name = "Sensory Aids / Prothesis / Skin Integrity",
                            RouteKey = "SkinSensoryAid"
                        },
                        new
                        {
                            AssessmentTypeId = 9,
                            Name = "Progress Note",
                            RouteKey = "AcuteProgress"
                        },
                        new
                        {
                            AssessmentTypeId = 10,
                            Name = "Labs / Diagnostics / Blood",
                            RouteKey = "LabsDiagnosticsBlood"
                        },
                        new
                        {
                            AssessmentTypeId = 11,
                            Name = "Discharge Checklist",
                            RouteKey = "DischargeChecklist"
                        },
                        new
                        {
                            AssessmentTypeId = 12,
                            Name = "Consults / Current Illness",
                            RouteKey = "ConsultCurrentIllness"
                        });
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.AcuteProgress", b =>
                {
                    b.Property<int>("AcuteProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcuteProgressId"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcuteProgressId");

                    b.ToTable("AcuteProgresses");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Adl", b =>
                {
                    b.Property<int>("AdlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADLsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdlId"));

                    b.Property<DateTime?>("BathDate")
                        .HasColumnType("DATE");

                    b.Property<string>("DentureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FootCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouthCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teeth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubShowerOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurningFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdlId");

                    b.ToTable("ADLs", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Behaviour", b =>
                {
                    b.Property<int>("BehaviourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BehaviourID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BehaviourId"));

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BehaviourId");

                    b.ToTable("Behaviour", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Cognitive", b =>
                {
                    b.Property<int>("CognitiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CognitiveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CognitiveId"));

                    b.Property<string>("Confusion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOC");

                    b.Property<string>("Mmse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MMSE");

                    b.Property<string>("Speech")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CognitiveId");

                    b.ToTable("Cognitive", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Consult", b =>
                {
                    b.Property<int>("ConsultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultId"));

                    b.Property<string>("ConsultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateReplied")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateSent")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("ConsultId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consults");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.DischargeChecklist", b =>
                {
                    b.Property<int>("DischargeChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DischargeChecklistId"));

                    b.Property<string>("ArrangeTransportationComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ArrangeTransportationCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ArrangeTransportationInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ArrangeTransportationNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("AssessBlisterPackComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("AssessBlisterPackCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AssessBlisterPackInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("AssessBlisterPackNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("CompletePASSComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CompletePASSCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CompletePASSInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("CompletePASSNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("CompleteTOAComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CompleteTOACompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CompleteTOAInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("CompleteTOANotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ConsultGeriatricNavComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ConsultGeriatricNavCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ConsultGeriatricNavInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ConsultGeriatricNavNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("CreateHomeChartComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CreateHomeChartCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CreateHomeChartInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("CreateHomeChartNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("DemonstrateAdminTechComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DemonstrateAdminTechCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DemonstrateAdminTechInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("DemonstrateAdminTechNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("EquipmentReadyComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EquipmentReadyCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EquipmentReadyInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("EquipmentReadyNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("FamilyAwareDischargeComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FamilyAwareDischargeCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FamilyAwareDischargeInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("FamilyAwareDischargeNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("FamilySupportComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FamilySupportCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FamilySupportInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("FamilySupportNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("GetAppointmentsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("GetAppointmentsCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("GetAppointmentsInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("GetAppointmentsNotApplicable")
                        .HasColumnType("bit");

                    b.Property<bool>("HighRiskDischarge")
                        .HasColumnType("bit");

                    b.Property<string>("NotifyContinuingCareComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NotifyContinuingCareCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NotifyContinuingCareInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("NotifyContinuingCareNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("NotifyPCNurseComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NotifyPCNurseCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NotifyPCNurseInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("NotifyPCNurseNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ObtainAffordMedsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ObtainAffordMedsCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ObtainAffordMedsInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ObtainAffordMedsNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("OrderTeachVTEComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OrderTeachVTECompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderTeachVTEInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("OrderTeachVTENotApplicable")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PrepareMedCalendarComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PrepareMedCalendarCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PrepareMedCalendarInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("PrepareMedCalendarNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ProvideFollowUpApptsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ProvideFollowUpApptsCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ProvideFollowUpApptsInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ProvideFollowUpApptsNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ProvideRxComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ProvideRxCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ProvideRxInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ProvideRxNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnHomeChartComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReturnHomeChartCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReturnHomeChartInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ReturnHomeChartNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnOwnMedsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReturnOwnMedsCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReturnOwnMedsInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ReturnOwnMedsNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnValuablesComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReturnValuablesCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReturnValuablesInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ReturnValuablesNotApplicable")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("TargetDischargeDate")
                        .HasColumnType("date");

                    b.Property<string>("TeachHighRiskMedsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TeachHighRiskMedsCompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TeachHighRiskMedsInitiatedDate")
                        .HasColumnType("date");

                    b.Property<bool>("TeachHighRiskMedsNotApplicable")
                        .HasColumnType("bit");

                    b.HasKey("DischargeChecklistId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("DischargeChecklists");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Elimination", b =>
                {
                    b.Property<int>("EliminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EliminationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EliminationId"));

                    b.Property<string>("CatheterInsertion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CatheterInsertionDate")
                        .HasColumnType("date");

                    b.Property<string>("CatheterSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOrNightProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastBowelMovement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Routine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EliminationId");

                    b.ToTable("Elimination", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.LabsDiagnosticsAndBlood", b =>
                {
                    b.Property<int>("LabsDiagnosticsAndBloodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabsDiagnosticsAndBloodId"));

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderedDate")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabsDiagnosticsAndBloodId");

                    b.HasIndex("PatientId");

                    b.ToTable("LabsDiagnosticsAndBloods");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.MobilityAndSafety", b =>
                {
                    b.Property<int>("MobilityAndSafetyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MobilityAndSafetyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobilityAndSafetyId"));

                    b.Property<string>("Aids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedAlarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrashMats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FallRiskScale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HipProtectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SideRails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transfer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobilityAndSafetyId");

                    b.ToTable("MobilityAndSafety", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Nutrition", b =>
                {
                    b.Property<int>("NutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NutritionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionId"));

                    b.Property<string>("Assist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Diet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedingTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FeedingTubeDate")
                        .HasColumnType("date");

                    b.Property<string>("Intake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NGTubeDate")
                        .HasColumnType("date");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("NutritionId");

                    b.ToTable("Nutrition", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.ProgressNote", b =>
                {
                    b.Property<int>("ProgressNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressNoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressNoteId"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME");

                    b.HasKey("ProgressNoteId");

                    b.ToTable("ProgressNote", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.SkinAndSensoryAid", b =>
                {
                    b.Property<int>("SkinAndSensoryAidsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkinAndSensoryAidsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkinAndSensoryAidsId"));

                    b.Property<string>("Glasses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HearingAidSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PressureUlcerRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinIntegrity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinIntegrityDressings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinIntegrityFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinIntegrityTurningSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurningScheduleFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkinAndSensoryAidsId");

                    b.ToTable("SkinAndSensoryAids");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ClassId");

                    b.HasIndex("InstructorId");

                    b.HasIndex(new[] { "JoinCode" }, "IX_Class_JoinCode")
                        .IsUnique();

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Nurse", b =>
                {
                    b.Property<int>("NurseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NurseId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInstructor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NurseId");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Nurse_PatientID")
                        .IsUnique()
                        .HasFilter("[PatientID] IS NOT NULL");

                    b.ToTable("Nurse", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("AdmittingDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BedNumber")
                        .HasColumnType("int");

                    b.Property<string>("CurrentIllness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFilename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsolationPrecautions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("NurseID");

                    b.Property<string>("PatientWristId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PatientWristID");

                    b.Property<string>("RoamAlertBracelet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("NurseId");

                    b.HasIndex(new[] { "PatientId" }, "IX_Patient_PatientID")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NurseId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RotationId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RotationId");

                    b.ToTable("Record", (string)null);
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Rotation", b =>
                {
                    b.Property<int>("RotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RotationId");

                    b.ToTable("Rotations");

                    b.HasData(
                        new
                        {
                            RotationId = 1,
                            Name = "LTC"
                        },
                        new
                        {
                            RotationId = 2,
                            Name = "Acute Care"
                        });
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.RotationAssessment", b =>
                {
                    b.Property<int>("RotationId")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentTypeId")
                        .HasColumnType("int");

                    b.HasKey("RotationId", "AssessmentTypeId");

                    b.HasIndex("AssessmentTypeId");

                    b.ToTable("RotationsAssessments");

                    b.HasData(
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 1
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 2
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 3
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 4
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 5
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 6
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 7
                        },
                        new
                        {
                            RotationId = 1,
                            AssessmentTypeId = 8
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 1
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 3
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 4
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 5
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 8
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 9
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 10
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 12
                        },
                        new
                        {
                            RotationId = 2,
                            AssessmentTypeId = 11
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.AssessmentSubmission", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.AssessmentType", "AssessmentType")
                        .WithMany()
                        .HasForeignKey("AssessmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NursingEducationalBackend.Models.Record", "Record")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentType");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.Consult", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.DischargeChecklist", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Assessments.LabsDiagnosticsAndBlood", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Class", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Nurse", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Nurse", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Patient", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Nurse", "Nurse")
                        .WithMany("Patients")
                        .HasForeignKey("NurseId");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Record", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NursingEducationalBackend.Models.Patient", "Patient")
                        .WithMany("Records")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NursingEducationalBackend.Models.Rotation", "Rotation")
                        .WithMany()
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Rotation");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.RotationAssessment", b =>
                {
                    b.HasOne("NursingEducationalBackend.Models.AssessmentType", "AssessmentType")
                        .WithMany()
                        .HasForeignKey("AssessmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NursingEducationalBackend.Models.Rotation", "Rotation")
                        .WithMany("RotationAssessments")
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentType");

                    b.Navigation("Rotation");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Nurse", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Patient", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Record", b =>
                {
                    b.Navigation("AssessmentSubmissions");
                });

            modelBuilder.Entity("NursingEducationalBackend.Models.Rotation", b =>
                {
                    b.Navigation("RotationAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
